//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iTeach.ModelDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class journal
    {
        public int Id { get; set; }
        public int IdStudent { get; set; }
        public int Evaluation { get; set; }
    
        public virtual Student Student { get; set; }
    }
}
