//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iTeach.ModelDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int IdSubject { get; set; }
        public int IdPay { get; set; }
        public string Parents { get; set; }
        public Nullable<int> Number { get; set; }
    
        public virtual journal journal { get; set; }
        public virtual Pay Pay { get; set; }
        public virtual Subject Subject { get; set; }
    }
}
